/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ApiInterviewRouteImport } from './routes/api/interview'
import { Route as ApiInterviewResetRouteImport } from './routes/api/interview-reset'
import { Route as ApiPublicInterviewRouteImport } from './routes/api/public/interview'

const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewRoute = ApiInterviewRouteImport.update({
  id: '/api/interview',
  path: '/api/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewResetRoute = ApiInterviewResetRouteImport.update({
  id: '/api/interview-reset',
  path: '/api/interview-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInterviewRoute = ApiPublicInterviewRouteImport.update({
  id: '/api/public/interview',
  path: '/api/public/interview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/chat': typeof ChatRoute
  '/api/interview': typeof ApiInterviewRoute
  '/api/interview-reset': typeof ApiInterviewResetRoute
  '/api/public/interview': typeof ApiPublicInterviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/chat': typeof ChatRoute
  '/api/interview': typeof ApiInterviewRoute
  '/api/interview-reset': typeof ApiInterviewResetRoute
  '/api/public/interview': typeof ApiPublicInterviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/chat': typeof ChatRoute
  '/api/interview': typeof ApiInterviewRoute
  '/api/interview-reset': typeof ApiInterviewResetRoute
  '/api/public/interview': typeof ApiPublicInterviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/chat'
    | '/api/interview'
    | '/api/interview-reset'
    | '/api/public/interview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/chat' | '/api/interview' | '/api/interview-reset' | '/api/public/interview'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/chat'
    | '/api/interview'
    | '/api/interview-reset'
    | '/api/public/interview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ChatRoute: typeof ChatRoute
  ApiInterviewRoute: typeof ApiInterviewRoute
  ApiInterviewResetRoute: typeof ApiInterviewResetRoute
  ApiPublicInterviewRoute: typeof ApiPublicInterviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview': {
      id: '/api/interview'
      path: '/api/interview'
      fullPath: '/api/interview'
      preLoaderRoute: typeof ApiInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview-reset': {
      id: '/api/interview-reset'
      path: '/api/interview-reset'
      fullPath: '/api/interview-reset'
      preLoaderRoute: typeof ApiInterviewResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/interview': {
      id: '/api/public/interview'
      path: '/api/public/interview'
      fullPath: '/api/public/interview'
      preLoaderRoute: typeof ApiPublicInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ChatRoute: ChatRoute,
  ApiInterviewRoute: ApiInterviewRoute,
  ApiInterviewResetRoute: ApiInterviewResetRoute,
  ApiPublicInterviewRoute: ApiPublicInterviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
